### ISSUE TITLE
CircleCI-ssh

### ISSUE THREAD

**Issue by SampsonM** [jdblischak/blog.jdblischak.com#2]
Hello!

In the section on:
    "Add the private key to CircleCI"

You say you can name the key whatever you like, but in fact it should be named 'github.com'.

"You can put whatever you like in the Hostname field to remind you that this key is for pushing to GitHub."

Thanks for the guide!!

**Comment by jdblischak** [comment]
@SampsonM Thanks so much for taking the time to alert me to this error. I see now in the [CircleCI documentation](https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key) that it states it must be "github.com"

> Go to your project settings, click on SSH Keys, and “Add SSH key”, and add the private key you created in step 1. In the “Hostname” field, enter “github.com”, and press the submit button.

I update the blog post accordingly
